### ISSUE TITLE
404 'unauthorized permission requested' for non public boards

### ISSUE THREAD

**Issue by rooreynolds** [rooreynolds/trello-show#1]
Supplying `key` and `board` works when the board is public. When it's a private board, it currently doesn't attempt to authenticate, resulting in a 404 `unauthorized permission requested` error.

**Comment by rooreynolds** [comment]
Documentation on getting a token: https://trello.com/docs/gettingstarted/index.html#getting-a-token-from-a-user

Quick and dirty:
1. `https://trello.com/1/authorize?key=[THE_APP_KEY]&name=trello-show&expiration=never&response_type=token` returns a token
2. `https://api.trello.com/1/board/[BOARD_ID]?cards=open&lists=open&checklists=all&key=[APP_KEY]&token=[USER_TOKEN]`

**Comment by andemx** [comment]
> Quick and dirty:
> 1. `https://trello.com/1/authorize?key=[THE_APP_KEY]&name=trello-show&expiration=never&response_type=token` returns a token
> 2. `https://api.trello.com/1/board/[BOARD_ID]?cards=open&lists=open&checklists=all&key=[APP_KEY]&token=[USER_TOKEN]`

all what the api auth doc should say nothing else.
